/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvedeniyaRouteImport } from './routes/svedeniya'
import { Route as MediaRouteImport } from './routes/media'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherIdRouteImport } from './routes/teacher.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LineIdRouteImport } from './routes/line.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as ApiPublicStorageExportRouteImport } from './routes/api/public/storage-export'

const SvedeniyaRoute = SvedeniyaRouteImport.update({
  id: '/svedeniya',
  path: '/svedeniya',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIdRoute = TeacherIdRouteImport.update({
  id: '/teacher/$id',
  path: '/teacher/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LineIdRoute = LineIdRouteImport.update({
  id: '/line/$id',
  path: '/line/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStorageExportRoute = ApiPublicStorageExportRouteImport.update({
  id: '/api/public/storage-export',
  path: '/api/public/storage-export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/media': typeof MediaRoute
  '/svedeniya': typeof SvedeniyaRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/storage-export': typeof ApiPublicStorageExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/media': typeof MediaRoute
  '/svedeniya': typeof SvedeniyaRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/storage-export': typeof ApiPublicStorageExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/contacts': typeof ContactsRoute
  '/history': typeof HistoryRoute
  '/media': typeof MediaRoute
  '/svedeniya': typeof SvedeniyaRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/storage-export': typeof ApiPublicStorageExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/contacts'
    | '/history'
    | '/media'
    | '/svedeniya'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin/'
    | '/api/public/storage-export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/contacts'
    | '/history'
    | '/media'
    | '/svedeniya'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin'
    | '/api/public/storage-export'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/contacts'
    | '/history'
    | '/media'
    | '/svedeniya'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin/'
    | '/api/public/storage-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  ContactsRoute: typeof ContactsRoute
  HistoryRoute: typeof HistoryRoute
  MediaRoute: typeof MediaRoute
  SvedeniyaRoute: typeof SvedeniyaRoute
  AdminSectionRoute: typeof AdminSectionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  LineIdRoute: typeof LineIdRoute
  PSlugRoute: typeof PSlugRoute
  TeacherIdRoute: typeof TeacherIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicStorageExportRoute: typeof ApiPublicStorageExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/svedeniya': {
      id: '/svedeniya'
      path: '/svedeniya'
      fullPath: '/svedeniya'
      preLoaderRoute: typeof SvedeniyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$id': {
      id: '/teacher/$id'
      path: '/teacher/$id'
      fullPath: '/teacher/$id'
      preLoaderRoute: typeof TeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/$id': {
      id: '/line/$id'
      path: '/line/$id'
      fullPath: '/line/$id'
      preLoaderRoute: typeof LineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/storage-export': {
      id: '/api/public/storage-export'
      path: '/api/public/storage-export'
      fullPath: '/api/public/storage-export'
      preLoaderRoute: typeof ApiPublicStorageExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  ContactsRoute: ContactsRoute,
  HistoryRoute: HistoryRoute,
  MediaRoute: MediaRoute,
  SvedeniyaRoute: SvedeniyaRoute,
  AdminSectionRoute: AdminSectionRoute,
  AdminLoginRoute: AdminLoginRoute,
  LineIdRoute: LineIdRoute,
  PSlugRoute: PSlugRoute,
  TeacherIdRoute: TeacherIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicStorageExportRoute: ApiPublicStorageExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
