/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherIdRouteImport } from './routes/teacher.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LineIdRouteImport } from './routes/line.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIdRoute = TeacherIdRouteImport.update({
  id: '/teacher/$id',
  path: '/teacher/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LineIdRoute = LineIdRouteImport.update({
  id: '/line/$id',
  path: '/line/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/login': typeof AdminLoginRoute
  '/line/$id': typeof LineIdRoute
  '/p/$slug': typeof PSlugRoute
  '/teacher/$id': typeof TeacherIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/$section'
    | '/admin/login'
    | '/line/$id'
    | '/p/$slug'
    | '/teacher/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSectionRoute: typeof AdminSectionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  LineIdRoute: typeof LineIdRoute
  PSlugRoute: typeof PSlugRoute
  TeacherIdRoute: typeof TeacherIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/$id': {
      id: '/teacher/$id'
      path: '/teacher/$id'
      fullPath: '/teacher/$id'
      preLoaderRoute: typeof TeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/$id': {
      id: '/line/$id'
      path: '/line/$id'
      fullPath: '/line/$id'
      preLoaderRoute: typeof LineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSectionRoute: AdminSectionRoute,
  AdminLoginRoute: AdminLoginRoute,
  LineIdRoute: LineIdRoute,
  PSlugRoute: PSlugRoute,
  TeacherIdRoute: TeacherIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
